url: http://vlad-shcherbina.github.io
baseurl: /
author: Vlad Shcherbina
email: vlad.shcherbina@gmail.com
title: Random stuff
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
